<div class="container h-100">
	<div class="row p-0 m-0 h-100">
		<div class="col-sm-12 d-flex justify-content-center align-items-center">
			<div class="text-center" style="max-width: 600px;padding: 25px;background: #fff;box-shadow: 3px 3px 20px rgba(0, 0, 0, .3);border-radius:3px;">
				<h3>Conta criada com sucesso.</h3>
				<a class="btn btn-outline-primary d-block" href="/">Efetuar Login</a>
			</div>
		</div>
	</div>
</div>