<div class="container h-100 p-0">
	<div class="row p-0 m-0 h-100">
		<div class="col-sm-12 p-0 d-flex justify-content-center align-items-center">
			<div class="boxForm w-100 h-100 d-flex align-items-center justify-content-center" style="max-width:400px; max-height: 400px;">
				<div class="w-100">
					<div class="iconImg">
					</div>
					<form action="/autenticar" method="post">
						<div class="mb-3 has-validation">
							<!-- <label for="validationCustom01" class="form-label">E-mail:</label> -->
							<input type="text" class="form-control" id="validationCustom01" name="email" placeholder="E-mail:">
							<div class="valid-feedback">
								confirmado
							</div>
							<div class="invalid-feedback">
								Login inválido
							</div>
						</div>
						<div class="mb-3 has-validation">
							<!-- <label for="exampleInputPassword1" class="form-label">Senha:</label> -->
							<input type="password" class="form-control" id="exampleInputPassword1" name="senha" placeholder="Senha:">
							<div class="invalid-feedback">
								senha invalida
							</div>
						</div>
						<?php if(isset($this->view->loginErr) && $this->view->loginErr != null) { ?>
							<div>
								<p class="text-danger"><?=$this->view->loginErr?></p>
							</div>
						<?php } ?>
						<button type="submit" class="btn">Enviar</button>
						<p class="mt-3">Não possui uma conta? <a href="/inscreverse">Criar conta</a></p>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- <script>
	// Example starter JavaScript for disabling form submissions if there are invalid fields
	(function () {
		'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
  .forEach(function (form) {
  	form.addEventListener('submit', function (event) {
  		if (!form.checkValidity()) {
  			event.preventDefault()
  			event.stopPropagation()
  		}

  		form.classList.add('was-validated')
  	}, false)
  })
})()
</script> -->