<div class="container h-100 p-0">
	<div class="row p-0 m-0 h-100">
		<div class="col-sm-12 p-0 d-flex align-items-center justify-content-center">
			<div class="boxForm">
				<div class="iconImg">
				</div>
				<?php if(isset($this->view->emailExi) && $this->view->emailExi != null) { ?>
					<div>
						<h5 class="text-danger"><?= $this->view->emailExi ?></h5>
					</div>
				<?php } ?>
				<form action="/registrar" method="post">
					<div class="mb-3 has-validation">
						<!-- <label for="validationCustom01" class="form-label">Nome Completo:</label> -->
						<?php if(isset($this->view->validaForm['name']) && $this->view->validaForm['name'] == false) { ?>
							<div>
								<p class="text-danger">Informe um nome válido. *</p>
							</div>
						<?php } ?>
						<input type="text" class="form-control" id="validationCustom01" placeholder="Nome completo:" name="nome" value="<?= $this->view->validaForm['name']?>">
						<div class="valid-feedback">
							confirmado
						</div>
						<div class="invalid-feedback">
							inválido
						</div>
					</div>
					<div class="mb-3 has-validation">
						<!-- <label for="email" class="form-label">E-mail:</label> -->
						<?php if(isset($this->view->validaForm['email']) && $this->view->validaForm['email'] == false) { ?>
							<div>
								<p class="text-danger">E-mail inválido, tente novamente. *</p>
							</div>
						<?php } ?>
						<input type="text" class="form-control" id="email" placeholder="E-mail:" name="email" value="<?= $this->view->validaForm['email']?>">
						<div class="valid-feedback">
							confirmado
						</div>
						<div class="invalid-feedback">
							inválido
						</div>
					</div>
					<div class="mb-3 has-validation">
						<!-- <label for="exampleInputPassword1" class="form-label">Senha:</label> -->
						<?php if(isset($this->view->validaForm['senha']) && $this->view->validaForm['senha'] == false) { ?>
							<div>
								<p class="text-danger">Critérios de senha inválidos, tente novamente. *</p>
							</div>
						<?php } ?>
						<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Senha:" name="senha" value="<?= $this->view->validaForm['senha']?>">
						<div class="invalid-feedback">
							senha invalida
						</div>
					</div>
					<div class="mb-3 termos">
						<p>Ao confirmar o cadastro você aceita os termos de uso e politica de privacidade de dados, conforme os termos da LGPD.</p>
					</div>
					<button type="submit" class="btn">Enviar</button>
					<p class="mt-3">Efetuar Login <a href="/">Inicio</a></p>
				</form>
			</div>
		</div>
	</div>
</div>

<!-- <script>
	// Example starter JavaScript for disabling form submissions if there are invalid fields
	(function () {
		'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
  .forEach(function (form) {
  	form.addEventListener('submit', function (event) {
  		if (!form.checkValidity()) {
  			event.preventDefault()
  			event.stopPropagation()
  		}

  		form.classList.add('was-validated')
  	}, false)
  })
})()
</script> -->